"use client"
import './globals.css'
// import  { Metadata } from 'next'
import  {NextUIProvider} from '@nextui-org/react'
import { Inter } from 'next/font/google'
import Navbar from "./navbar"

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <NextUIProvider>
      <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
      </NextUIProvider>
    </html>
  )
}
